### ISSUE TITLE
Common.GitHub.proj sets GitHubProject to Corvus.Extensions

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Retry#1]
This:

```xml
<GitHubProject>Corvus.Extensions</GitHubProject>
```

in https://github.com/corvus-dotnet/Corvus.Retry/blob/master/Solutions/Common.GitHub.proj#L4 is presumably a cut and paste error.

**Comment by HowardvanRooijen** [comment]
Fixed in https://github.com/corvus-dotnet/Corvus.Retry/pull/9
