### ISSUE TITLE
Add GitVersion.yml to enable feature branch commit distance versioning

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Retry#2]
By default, GitVersion applies a versioning scheme for certain branches based on the number of commits since the last commit definitively determined to be a particular version. This is useful for preview builds. If the last version was, say, 1.2.3, something one commit downstream of this will have `+1` appended to its version string, and something 4 commits downstream will get `+4` and so on. 

This is useful when committing work in progress, because each build gets a distinct version string. Work on the `develop` branch gets an `alpha` tag by default so builds launched for that branch will have version numbers such as `1.3.0-alpha+5`.

Unfortunately, the default for feature branches is not to use this. The upshot is that no matter how many different commits you trigger builds for on a particular feature branch, they will all get the same version number. This is problematic if you want to publish the resulting NuGet packages somewhere.

The config should be changed so as to enable this same form of versioning for feature branches. (For reasons lost in the mists of time, the way to enable this is to set the `mode` for the branch to `ContinuousDeployment`.)

**Comment by HowardvanRooijen** [comment]
Fixed in https://github.com/corvus-dotnet/Corvus.Retry/pull/9
